
name: build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: 🔔 checkout
      uses: actions/checkout@v3

    - name: 🔧 setup node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: 📦 install dependencies
      run: npm ci

    - name: 🔨 build
      run: npm run build-production -s

    - name: 🧪 test
      run: npm test
